build: refine workflow configuration
appiepollo14/quarkus-realworld-api pull request #74
Opened 2024-10-01 01:33 UTC by codespearhead

- Set workflow timeout for better job control
- Implement Maven dependency caching for faster builds
- Use Maven Wrapper (mvnw) to prevent development environment discrepancies
- Enable batch mode in Maven to reduce log clutter from download progress
- Trigger workflow on push and pull request events for the master branch
- Replace fixed 10-second sleep with a dynamic readiness check for the app

2024-10-01 06:07 UTC, appiepollo14 requested changes
Thank you for contributing to the repo. A great improvement in the workflow. I've added a few minor comments which can be resolved easily.

2024-10-01 06:07 UTC, appiepollo14 commented on .github/workflows/maven.yml
> +      - master
I've recently removed this, as we only merge to master via PR's. Now the workflow is triggered after merging a PR, which is IMO a waste of cycles. Can you explain why you want this trigger to be added?

2024-10-01 06:07 UTC, appiepollo14 commented on .github/workflows/maven.yml
> -    services:
Are we testing now against devServices PostGres? I don't see that in any code changes though..

2024-10-01 06:07 UTC, appiepollo14 commented on .github/workflows/maven.yml
> +      - name: Run tests
All of the caching and mvnw related changes, are great and very welcome!

2024-10-01 06:07 UTC, appiepollo14 commented on .github/workflows/maven.yml
> +          nohup java -jar target/quarkus-app/quarkus-run.jar > app.log 2>&1 &
Even though there is a timeout on the whole workflow, I'ld love to see an exit clause here, after X tries fail the workflow for example. Something like: https://github.com/argoproj/argo-cd/blob/master/.github/workflows/ci-build.yaml#L493-L500

2024-10-01 14:00 UTC, codespearhead commented on .github/workflows/maven.yml
> +      - master
As long as all updates to the central branch (master) are made through pull requests, and the git history remains linear (i.e., all PRs are rebased onto the central branch before merging using `git checkout feature_branch && git pull --rebase origin master`, instead of `git checkout feature_branch && git merge master`, it's indeed unnecessary.

Go to [Repository Page> Settings > Branches > Add rule](https://github.com/appiepollo14/quarkus-realworld-api/settings/branch_protection_rules/new) and follow these steps to enforce those constraints:

| Required  | Setting                                                | Value   |
|-----------|--------------------------------------------------------|---------|
| Yes       | Branch name pattern                                    | master  |
| Yes       | Require linear history                                 | ENABLE  |
| Yes       | Require a pull request before merging                  | ENABLE  |
| No        | Require a pull request before merging > Require approvals | 1       |
| No        | Require signed commits                                 | ENABLE  |
| Yes       | Do not allow bypassing the above settings              | ENABLE  |
| Yes       | Allow force pushes                                     | DISABLE |
| Yes       | Allow deletions                                        | DISABLE |

2024-10-01 18:44 UTC, appiepollo14 commented on .github/workflows/maven.yml
> +      - master
this is already implmented through rules.

2024-10-01 21:30 UTC, codespearhead commented on .github/workflows/maven.yml
> -    services:
It's not clear to me why Postgres is included in the project. Should both the Maven and K6 tests be run against both H2 and Postgres?

2024-10-03 16:55 UTC, appiepollo14 commented on .github/workflows/maven.yml
> -    services:
No, it should use PostgreSQL as single kind of database. I've merged: https://github.com/appiepollo14/quarkus-realworld-api/pull/75 for starters. Will focus on a separate PR for getting rid of the H2 for the test profile as well. For your PR, you should rebase on upstream and take into account the PostgreSQL database kind.

2024-10-07 13:27 UTC, appiepollo14 approved these changes
Perfect. Many thanks!!

2024-10-07 13:27 UTC, merged